In [2]:
import pandas as pd
import numpy as np

# Tensorflow

In [1]:
import tensorflow as tf 
conf = tf.contrib.metrics.confusion_matrix([0, 1, 2, 3], [0, 2, 2, 3]) 
# ==>
#       [[0 0 0 0 0]
#        [0 0 1 0 0]
#        [0 0 1 0 0]
#        [0 0 0 0 0]
#        [0 0 0 0 1]]

with tf.Session() as sess:
        print(sess.run(conf))

[[1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]]


# Pandas - LIST 

In [5]:
path = "../../data/FRFLO/datasc.csv"

columns = pd.read_csv( tf.gfile.Open(path), sep=None, skipinitialspace=True,  engine="python" ,skiprows=0, nrows=1)
dst = pd.read_csv( tf.gfile.Open(path), sep=None, skipinitialspace=True,  engine="python" ,skiprows=0*10+1, 
               nrows=10, names = columns.columns)

In [1]:
list = [1,2,3,4,5,6]

In [2]:
list.pop(1)

2

In [4]:
ytb = [2, 4, 5]
label_mask = np.zeros_like(ytb)
label_mask[:] = 1 #label_mask[0:1000] = 1
label_mask

array([1, 1, 1])

In [3]:
COL_DS = "../../data/FRFLO/datac.csv"
col_df = pd.read_csv(COL_DS, index_col=2, sep=',', usecols=[0,1,2,3])    
# COL_DS     = "./../_zfp/data/FRFLO/colcom.csv"
# col_df = pd.read_csv(COL_DS, index_col=0, sep=',', usecols=[0,1,2,3])
# print(col_df)

In [11]:
index = col_df.columns

In [15]:
index = index.delete(1)

In [16]:
index

Index(['cc', 'fp'], dtype='object')

In [5]:
sample_z = np.random.normal(0, 1, size=(100))
mask_z = np.random.randint(2, size=100)    

# sample_z*mask_z

In [19]:
indx = [ "A", "B" ]
df_entry = pd.Series(index=indx)
df_entry = df_entry.fillna(0)
df_entry["A"]=0.01
# df_entry *= 0
# df_entry = df_entry.replace(0, np.nan)

df_entry

A    0.01
B    0.00
dtype: float64

# ranges - tupples - functions

In [17]:
range(20)

range(0, 20)

In [18]:
range(20, 40)

range(20, 40)

In [13]:
import operator 
def test(): 
    return 1, 1 

a , b = 2, 4 
# a, b = ( (a, b) + test() ) NOT WORKING
a,b = tuple(map(operator.add, (a,b), test()))

ret = (1, 2)
# ret += test()  NOT WORKING
ret = tuple(map(operator.add,ret,test()))
ret
a, b


(3, 5)

In [28]:
def funct(i): 
    return "hi " + str(i)

arr = [ 1, 2 , 3 ]
promp = "m:{0:15} - R-{1:5}   ||".format("1", "2") 
promp = promp + str([ funct(arr[x]) for x in range(len(arr)) ]  )
# promp = promp +  str( funct(arr[x]) for x in range(3) )

print(promp)


m:1               - R-2       ||['hi 1', 'hi 2', 'hi 3']


In [34]:
lz = [0] * 10

In [31]:
lz

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Files

In [1]:
# write a file text 
file = '../../data/FRFLO/atx.txt'
f = open(file, 'w')
for i in range(10):
     f.write("This is line %d\r\n" % (i+1))
f.close()

In [1]:
ev_ac = 20.2
print("E Ac:", ev_ac)

E Ac: 20.2


In [ ]:
import json

# test json ... information lost for json read 
json_str = '''[{ "m":"8989", "c674" :0.00454545454545 , "c950" :0.0045 }] '''
json_data = json.loads(json_str)
print(type(json_data))
